[package]
name = "scorch"
version = "1.0.0"
edition = "2021"

[dependencies]
colored = "2.0"
strip-ansi-escapes = "0.1.1"
rustc-hash = "1.1"
once_cell = "1.18"
regex = "1.11.1"
stack_box = "1.5.1"
sh = { path = "../sh" }
